<?php

declare(strict_types=1);

namespace Ngramx\Tests\Unit\Postmaclone;

use Ngramx\Postmaclone\Connect\PostmacloneConnectComposeOverride;
use Ngramx\Postmaclone\Connect\PostmacloneConnectLockData;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Yaml\Yaml;

class PostmacloneConnectComposeOverrideTest extends TestCase
{
    private string $dir;

    protected function setUp(): void
    {
        $this->dir = sys_get_temp_dir() . '/pm-compose-override-' . uniqid('', true);
        mkdir($this->dir, 0700, true);
    }

    protected function tearDown(): void
    {
        @unlink($this->dir . '/docker-compose.yml');
        @unlink($this->dir . '/docker-compose.override.yml');
        @rmdir($this->dir);
    }

    public function test_detects_services_with_db_host_in_compose_environment(): void
    {
        file_put_contents($this->dir . '/docker-compose.yml', <<<'YAML'
services:
  app:
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  reverb:
    environment:
      DB_HOST: db
  nginx:
    image: nginx:alpine
YAML);

        $override = new PostmacloneConnectComposeOverride();

        $this->assertSame(['app', 'reverb'], $override->databaseServiceNames($this->dir . '/docker-compose.yml'));
    }

    public function test_apply_patches_db_environment_for_database_services(): void
    {
        file_put_contents($this->dir . '/docker-compose.yml', <<<'YAML'
services:
  app:
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  reverb:
    environment:
      DB_HOST: db
YAML);

        $lock = new PostmacloneConnectLockData(
            mode: PostmacloneConnectLockData::MODE_TUNNEL,
            engine: 'postgres',
            connectedAt: '2026-01-01T00:00:00+00:00',
            host: 'host.docker.internal',
            port: 15433,
            database: 'earl_kendrick_core_prod_anon',
            username: 'anon',
            password: 'secret',
            databaseUrl: 'postgresql://anon:secret@host.docker.internal:15433/earl_kendrick_core_prod_anon',
            ideHost: '127.0.0.1',
            idePort: 15433,
            localPort: 15433,
        );

        (new PostmacloneConnectComposeOverride())->apply($this->dir . '/docker-compose.yml', $lock);

        $this->assertFileExists($this->dir . '/docker-compose.override.yml');
        $parsed = Yaml::parseFile($this->dir . '/docker-compose.override.yml');
        $this->assertIsArray($parsed);
        $this->assertSame('host.docker.internal', $parsed['services']['app']['environment']['DB_HOST']);
        $this->assertSame('15433', $parsed['services']['app']['environment']['DB_PORT']);
        $this->assertSame('earl_kendrick_core_prod_anon', $parsed['services']['app']['environment']['DB_DATABASE']);
        $this->assertSame(['host.docker.internal:host-gateway'], $parsed['services']['app']['extra_hosts']);
        $this->assertSame('host.docker.internal', $parsed['services']['reverb']['environment']['DB_HOST']);
    }

    public function test_remove_parses_ngramx_override_with_custom_compose_tags(): void
    {
        file_put_contents($this->dir . '/docker-compose.yml', <<<'YAML'
services:
  app:
    environment:
      DB_HOST: db
YAML);
        file_put_contents($this->dir . '/docker-compose.override.yml', <<<'YAML'
# Generated by Ngramx CLI - DO NOT EDIT MANUALLY

services:
  nginx:
    ports: !override
      - '8080:80'
  app:
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: '15433'
      DB_DATABASE: demo
    extra_hosts:
      - host.docker.internal:host-gateway
YAML);

        (new PostmacloneConnectComposeOverride())->remove($this->dir . '/docker-compose.yml');

        $content = file_get_contents($this->dir . '/docker-compose.override.yml');
        $this->assertIsString($content);
        $this->assertStringContainsString('ports: !override', $content);
        $this->assertStringNotContainsString('DB_HOST', $content);
        $this->assertStringNotContainsString('extra_hosts', $content);

        $parsed = Yaml::parse($content, Yaml::PARSE_CUSTOM_TAGS);
        $this->assertIsArray($parsed);
        $this->assertArrayHasKey('nginx', $parsed['services']);
        $this->assertArrayNotHasKey('app', $parsed['services']);
    }

    public function test_remove_clears_connect_db_overrides(): void
    {
        file_put_contents($this->dir . '/docker-compose.yml', <<<'YAML'
services:
  app:
    environment:
      DB_HOST: db
YAML);
        file_put_contents($this->dir . '/docker-compose.override.yml', <<<'YAML'
services:
  app:
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: "15433"
      DB_DATABASE: demo
      OTHER: keep
    extra_hosts:
      - host.docker.internal:host-gateway
YAML);

        (new PostmacloneConnectComposeOverride())->remove($this->dir . '/docker-compose.yml');

        $parsed = Yaml::parseFile($this->dir . '/docker-compose.override.yml');
        $this->assertIsArray($parsed);
        $this->assertSame(['OTHER' => 'keep'], $parsed['services']['app']['environment']);
        $this->assertArrayNotHasKey('extra_hosts', $parsed['services']['app']);
    }
}
