<?php

declare(strict_types=1);

namespace Ngramx\Docker;

use Ngramx\Worktree\WorktreeGitMount;
use Symfony\Component\Yaml\Yaml;

/**
 * Generates the Ngramx-managed docker-compose override file.
 *
 * The override carries three kinds of machine-generated changes, all of which
 * are re-derived from scratch on every run (so the file is safe to overwrite):
 *
 *   - port offsets, to avoid host port collisions between parallel stacks;
 *   - container-name prefixes, for namespace isolation;
 *   - a worktree git bind mount, so git resolves inside containers when the
 *     stack runs from a linked git worktree (see {@see WorktreeGitMount}).
 *
 * User customisations must NOT go in this file — they belong in
 * `docker-compose.user.yml`, which Ngramx layers last and never regenerates
 * (see {@see ComposeFiles}).
 */
class ComposeOverrideGenerator
{
    private const OVERRIDE_FILE = ComposeFiles::OVERRIDE_FILE;
    private const HEADER_COMMENT = <<<YAML
# Generated by Ngramx CLI - DO NOT EDIT MANUALLY
# This file is regenerated on every `ngramx up` / `ngramx review`.
# Put local customisations in docker-compose.user.yml instead — it is layered
# last and is never overwritten.
# Run 'ngramx down' to remove this file.

YAML;

    private readonly WorktreeGitMount $gitMount;

    public function __construct(?WorktreeGitMount $gitMount = null)
    {
        $this->gitMount = $gitMount ?? new WorktreeGitMount();
    }

    /**
     * Generate the override file with port offsets, namespace prefixes and a
     * worktree git bind mount as needed. A no-op when none of those apply.
     */
    public function generate(string $composeFile, int $portOffset, ?string $namespacePrefix = null, bool $noHostMapping = false): void
    {
        // When the stack runs from a linked git worktree, bind-mount the parent
        // repo's shared git dir at the same absolute path the worktree's gitdir
        // pointer references, so git resolves inside containers instead of
        // crash-looping a `set -e` entrypoint. Detection only reads git
        // metadata next to the compose file.
        $gitCommonDir = $this->gitMount->resolve($this->projectDir($composeFile));

        if ($portOffset === 0 && $namespacePrefix === null && !$noHostMapping && $gitCommonDir === null) {
            // No override needed
            return;
        }

        if (!file_exists($composeFile)) {
            throw new \RuntimeException("Compose file not found: {$composeFile}");
        }

        // Parse original compose file
        $content = file_get_contents($composeFile);
        if ($content === false) {
            throw new \RuntimeException("Failed to read compose file: {$composeFile}");
        }

        $config = Yaml::parse($content);

        if (!isset($config['services'])) {
            return;
        }

        // Build override structure
        $override = [
            'services' => [],
        ];

        // Track if we need to remove ports (for noHostMapping)
        $servicesWithPorts = [];

        foreach ($config['services'] as $serviceName => $service) {
            $serviceOverride = [];

            // Handle port removal for no-host-mapping mode
            if ($noHostMapping && isset($service['ports'])) {
                // Mark this service as needing port removal
                $servicesWithPorts[] = $serviceName;
                $serviceOverride['ports'] = [];
            }
            // Handle port offset (only when not removing ports entirely)
            elseif (isset($service['ports']) && $portOffset > 0) {
                $newPorts = [];
                foreach ($service['ports'] as $portMapping) {
                    $newPort = $this->applyOffset($portMapping, $portOffset);
                    if ($newPort !== null) {
                        $newPorts[] = $newPort;
                    }
                }

                if (!empty($newPorts)) {
                    $serviceOverride['ports'] = $newPorts;
                }
            }

            // Handle container_name prefixing for namespace isolation
            if ($namespacePrefix !== null && isset($service['container_name'])) {
                // Prefix the container name with namespace
                $serviceOverride['container_name'] = $namespacePrefix . '-' . $service['container_name'];
            }

            // Bind-mount the worktree's parent git dir into build-context
            // services (the app plus any worker/reverb that builds from source
            // and runs the project entrypoint). Compose merges volumes by mount
            // target and environment by key, so existing config is preserved.
            if ($gitCommonDir !== null && $this->buildsFromSource($service)) {
                $serviceOverride['volumes'] = [$gitCommonDir . ':' . $gitCommonDir];
                $serviceOverride['environment'] = $this->gitSafeDirectoryEnv();
            }

            if (!empty($serviceOverride)) {
                $override['services'][$serviceName] = $serviceOverride;
            }
        }

        // Write override file next to the base compose file
        if (!empty($override['services'])) {
            $this->writeOverrideFile($override, $servicesWithPorts, $composeFile);
        }
    }

    /**
     * Resolve the directory that holds the compose file (and, for a worktree,
     * the `.git` pointer file we inspect). Falls back to the raw dirname when
     * the path cannot be realpath-resolved (e.g. it does not exist yet).
     */
    private function projectDir(string $composeFile): string
    {
        $real = realpath($composeFile);

        return $real !== false ? dirname($real) : dirname($composeFile);
    }

    /**
     * Whether a service is built from source (has a `build:` context). These are
     * the services whose containers run the project entrypoint and therefore
     * need git to resolve.
     *
     * @param mixed $service
     */
    private function buildsFromSource($service): bool
    {
        return is_array($service) && isset($service['build']);
    }

    /**
     * Environment that tells git inside the container to trust the bind-mounted
     * repository regardless of host/container uid mismatch, so the mounted
     * worktree git dir doesn't trip git's "dubious ownership" safety check and
     * abort the entrypoint.
     *
     * @return array<string, string>
     */
    private function gitSafeDirectoryEnv(): array
    {
        return [
            'GIT_CONFIG_COUNT' => '1',
            'GIT_CONFIG_KEY_0' => 'safe.directory',
            'GIT_CONFIG_VALUE_0' => '*',
        ];
    }

    /**
     * Delete the override file from the same directory as the base compose file.
     */
    public function cleanup(string $composeFile): void
    {
        $overridePath = $this->overridePath($composeFile);
        if (file_exists($overridePath)) {
            unlink($overridePath);
        }
    }

    /**
     * Apply port offset to a port mapping.
     *
     * Handles env-var interpolation in the host port (e.g. "${VAR:-3827}:4173")
     * by splitting on top-level colons only, so the interpolation block is left
     * intact instead of being corrupted into invalid Compose syntax.
     */
    private function applyOffset(mixed $portMapping, int $offset): ?string
    {
        if (!is_string($portMapping)) {
            // Long-format (array) port mappings are not offset here.
            return null;
        }

        $parts = PortMapping::split($portMapping);

        if (count($parts) === 2) {
            // "80:80" or "${VAR:-3827}:4173" format
            [$hostPort, $containerPort] = $parts;
            return PortMapping::offsetHostPort($hostPort, $offset) . ':' . $containerPort;
        }

        if (count($parts) === 3) {
            // "127.0.0.1:80:80" or "127.0.0.1:${VAR:-3827}:4173" format
            [$interface, $hostPort, $containerPort] = $parts;
            return $interface . ':' . PortMapping::offsetHostPort($hostPort, $offset) . ':' . $containerPort;
        }

        // Container-only ("4173") or unrecognised shapes: preserve as-is so the
        // mapping is not dropped from the override file.
        return $portMapping;
    }

    /**
     * Resolve the path where the override file should live — always in the same
     * directory as the base compose file so that Docker Compose auto-discovery
     * and {@see ComposeFiles::layeredFiles()} both find it.
     */
    private function overridePath(string $composeFile): string
    {
        $dir = realpath($composeFile) !== false
            ? dirname((string) realpath($composeFile))
            : dirname($composeFile);

        return $dir . '/' . self::OVERRIDE_FILE;
    }

    /**
     * Write the override file to disk
     *
     * @param array<string, mixed> $override
     * @param string[] $servicesWithEmptyPorts Services that need ports completely removed
     */
    private function writeOverrideFile(array $override, array $servicesWithEmptyPorts, string $composeFile): void
    {
        // Docker Compose v2 merges arrays by default
        // Use !override tag to force replacement instead of merging
        $yaml = Yaml::dump($override, 10, 2);

        // Add !override tag to ports arrays to prevent merging with base file
        // This ensures only the offset ports are used, not the original + offset
        $yaml = preg_replace('/^(\s+ports:)$/m', '$1 !override', $yaml) ?? $yaml;

        // For services with empty ports (no-host-mapping), use !reset [] to clear ports entirely
        // Docker Compose doesn't accept "!override []" but accepts "!reset []" to clear values
        // Note: Yaml::dump outputs empty arrays as "{ }" (inline empty map)
        $yaml = preg_replace('/^(\s+ports:) \{  \}$/m', '$1 !reset []', $yaml) ?? $yaml;

        $content = self::HEADER_COMMENT . $yaml;

        $overridePath = $this->overridePath($composeFile);
        file_put_contents($overridePath, $content);
    }
}
