<?php

declare(strict_types=1);

namespace Ngramx\Docker;

use Symfony\Component\Yaml\Yaml;

/**
 * Generates docker-compose override files with port offsets
 */
class ComposeOverrideGenerator
{
    private const OVERRIDE_FILE = 'docker-compose.override.yml';
    private const HEADER_COMMENT = <<<YAML
# Generated by Ngramx CLI - DO NOT EDIT MANUALLY
# This file is automatically created to prevent port conflicts
# Run 'ngramx down' to remove this file

YAML;

    /**
     * Generate override file with port offset and container name handling
     */
    public function generate(string $composeFile, int $portOffset, ?string $namespacePrefix = null, bool $noHostMapping = false): void
    {
        if ($portOffset === 0 && $namespacePrefix === null && !$noHostMapping) {
            // No override needed
            return;
        }

        if (!file_exists($composeFile)) {
            throw new \RuntimeException("Compose file not found: {$composeFile}");
        }

        // Parse original compose file
        $content = file_get_contents($composeFile);
        if ($content === false) {
            throw new \RuntimeException("Failed to read compose file: {$composeFile}");
        }

        $config = Yaml::parse($content);

        if (!isset($config['services'])) {
            return;
        }

        // Build override structure
        $override = [
            'services' => [],
        ];

        // Track if we need to remove ports (for noHostMapping)
        $servicesWithPorts = [];

        foreach ($config['services'] as $serviceName => $service) {
            $serviceOverride = [];

            // Handle port removal for no-host-mapping mode
            if ($noHostMapping && isset($service['ports'])) {
                // Mark this service as needing port removal
                $servicesWithPorts[] = $serviceName;
                $serviceOverride['ports'] = [];
            }
            // Handle port offset (only when not removing ports entirely)
            elseif (isset($service['ports']) && $portOffset > 0) {
                $newPorts = [];
                foreach ($service['ports'] as $portMapping) {
                    $newPort = $this->applyOffset($portMapping, $portOffset);
                    if ($newPort !== null) {
                        $newPorts[] = $newPort;
                    }
                }

                if (!empty($newPorts)) {
                    $serviceOverride['ports'] = $newPorts;
                }
            }

            // Handle container_name prefixing for namespace isolation
            if ($namespacePrefix !== null && isset($service['container_name'])) {
                // Prefix the container name with namespace
                $serviceOverride['container_name'] = $namespacePrefix . '-' . $service['container_name'];
            }

            if (!empty($serviceOverride)) {
                $override['services'][$serviceName] = $serviceOverride;
            }
        }

        // Write override file
        if (!empty($override['services'])) {
            $this->writeOverrideFile($override, $servicesWithPorts);
        }
    }

    /**
     * Delete the override file
     */
    public function cleanup(): void
    {
        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        if (file_exists($overridePath)) {
            unlink($overridePath);
        }
    }

    /**
     * Apply port offset to a port mapping.
     *
     * Handles env-var interpolation in the host port (e.g. "${VAR:-3827}:4173")
     * by splitting on top-level colons only, so the interpolation block is left
     * intact instead of being corrupted into invalid Compose syntax.
     */
    private function applyOffset(mixed $portMapping, int $offset): ?string
    {
        if (!is_string($portMapping)) {
            // Long-format (array) port mappings are not offset here.
            return null;
        }

        $parts = PortMapping::split($portMapping);

        if (count($parts) === 2) {
            // "80:80" or "${VAR:-3827}:4173" format
            [$hostPort, $containerPort] = $parts;
            return PortMapping::offsetHostPort($hostPort, $offset) . ':' . $containerPort;
        }

        if (count($parts) === 3) {
            // "127.0.0.1:80:80" or "127.0.0.1:${VAR:-3827}:4173" format
            [$interface, $hostPort, $containerPort] = $parts;
            return $interface . ':' . PortMapping::offsetHostPort($hostPort, $offset) . ':' . $containerPort;
        }

        // Container-only ("4173") or unrecognised shapes: preserve as-is so the
        // mapping is not dropped from the override file.
        return $portMapping;
    }

    /**
     * Write the override file to disk
     *
     * @param array<string, mixed> $override
     * @param string[] $servicesWithEmptyPorts Services that need ports completely removed
     */
    private function writeOverrideFile(array $override, array $servicesWithEmptyPorts = []): void
    {
        // Docker Compose v2 merges arrays by default
        // Use !override tag to force replacement instead of merging
        $yaml = Yaml::dump($override, 10, 2);

        // Add !override tag to ports arrays to prevent merging with base file
        // This ensures only the offset ports are used, not the original + offset
        $yaml = preg_replace('/^(\s+ports:)$/m', '$1 !override', $yaml) ?? $yaml;

        // For services with empty ports (no-host-mapping), use !reset [] to clear ports entirely
        // Docker Compose doesn't accept "!override []" but accepts "!reset []" to clear values
        // Note: Yaml::dump outputs empty arrays as "{ }" (inline empty map)
        $yaml = preg_replace('/^(\s+ports:) \{  \}$/m', '$1 !reset []', $yaml) ?? $yaml;

        $content = self::HEADER_COMMENT . $yaml;

        $overridePath = getcwd() . '/' . self::OVERRIDE_FILE;
        file_put_contents($overridePath, $content);
    }
}
