<?php

declare(strict_types=1);

namespace Ngramx\Agents;

/**
 * Keeps generated agent files out of git without ignoring hand-written ones.
 *
 * The managed block ignores only the files Ngramx regenerates. Project notes
 * in AGENTS.md, and any other file under .cursor/ or .claude/, stay tracked.
 */
final class AgentsGitignoreSynchronizer
{
    public const BEGIN = '# ngramx-agents-begin';

    public const END = '# ngramx-agents-end';

    private const LEGACY_COMMENT = '# Ngramx-generated agent files';

    public function sync(string $projectRoot): bool
    {
        $path = rtrim($projectRoot, '/') . '/.gitignore';
        $existing = is_file($path) ? file_get_contents($path) : '';
        if ($existing === false) {
            return false;
        }

        $block = $this->block();
        $updated = $this->upsert($existing, $block);
        if ($updated === $existing) {
            return false;
        }

        return file_put_contents($path, $updated) !== false;
    }

    public function block(): string
    {
        return implode("\n", [
            self::BEGIN,
            '# Generated by `ngramx sync-agents`. AGENTS.md stays version-controlled.',
            '# Hand-written rules and skills under .cursor/ and .claude/ stay tracked.',
            '/CLAUDE.md',
            '/.claude/rules/ngramx.md',
            '/.cursor/rules/ngramx.mdc',
            '/.github/copilot-instructions.md',
            '/.cursor/skills/ngramx-*/',
            '/.claude/skills/ngramx-*/',
            '# Previous CLI wrote these unprefixed folders. Safe to delete once that CLI is gone.',
            '/.cursor/skills/create-linear-tickets/',
            '/.cursor/skills/create-pr/',
            '/.cursor/skills/start-ticket/',
            '/.cursor/skills/update-pr/',
            '/.claude/skills/create-linear-tickets/',
            '/.claude/skills/create-pr/',
            '/.claude/skills/start-ticket/',
            '/.claude/skills/update-pr/',
            self::END,
            '',
        ]);
    }

    private function upsert(string $existing, string $block): string
    {
        $pattern = '/' . preg_quote(self::BEGIN, '/') . '.*?' . preg_quote(self::END, '/') . '\R?/s';
        if (preg_match($pattern, $existing) === 1) {
            $replaced = preg_replace($pattern, rtrim($block) . "\n", $existing, 1);

            return is_string($replaced) ? $replaced : $existing;
        }

        $withoutLegacy = $this->removeLegacyBlock($existing);
        if ($withoutLegacy !== $existing) {
            $trimmed = rtrim($withoutLegacy);

            return ($trimmed === '' ? '' : $trimmed . "\n\n") . $block;
        }

        if ($existing === '') {
            return $block;
        }

        $prefix = str_ends_with($existing, "\n") ? $existing : $existing . "\n";
        if (!str_ends_with($prefix, "\n\n")) {
            $prefix .= "\n";
        }

        return $prefix . $block;
    }

    private function removeLegacyBlock(string $existing): string
    {
        $lines = preg_split('/\R/', $existing);
        if ($lines === false) {
            return $existing;
        }

        $kept = [];
        $skipping = false;
        $removed = false;

        foreach ($lines as $line) {
            if (!$skipping && str_starts_with(trim($line), self::LEGACY_COMMENT)) {
                $skipping = true;
                $removed = true;
                continue;
            }

            if ($skipping) {
                if ($this->isLegacyIgnoreLine($line)) {
                    continue;
                }
                $skipping = false;
            }

            $kept[] = $line;
        }

        if (!$removed) {
            return $existing;
        }

        return implode("\n", $kept);
    }

    private function isLegacyIgnoreLine(string $line): bool
    {
        $trim = trim($line);
        if ($trim === '') {
            return false;
        }

        return preg_match(
            '#^/?(?:AGENTS\.md|CLAUDE\.md|\.claude/CLAUDE\.md|\.claude/rules/ngramx\.md|\.cursor/rules/ngramx\.mdc|\.github/copilot-instructions\.md|\.cursor/skills/\S+|\.claude/skills/\S+)$#',
            $trim
        ) === 1;
    }
}
