<?php

declare(strict_types=1);

namespace Ngramx\Agents;

/**
 * Builds the short index written into generated agent files.
 *
 * The index is a list of one-liners that point at skill files. The skill
 * files hold the actual instructions and are generated on demand. This stays
 * generic so the same index is safe in every repository.
 */
final class AgentsManagedBodyProvider
{
    public function __construct(private readonly ?string $templatesRoot = null)
    {
    }

    public function getMarkdown(): string
    {
        $skills = (new SkillCatalog($this->templatesRoot))->discover();
        if ($skills === []) {
            return '';
        }

        $lines = [];
        foreach ($skills as $skill) {
            $lines[] = '- `' . $skill['generatedName'] . '` — ' . $skill['summary'];
        }

        return implode("\n", [
            '# Ngramx',
            '',
            'These notes apply to any repository that uses Ngramx. Put project-specific instructions in `AGENTS.md` and in hand-written files under `.cursor/` or `.claude/`. Ngramx does not modify `AGENTS.md`.',
            '',
            'The skills below are generated by `ngramx sync-agents` and are gitignored. Open the matching skill when the task fits. Do not copy skill text back into `AGENTS.md` or `CLAUDE.md`.',
            '',
            implode("\n", $lines),
        ]);
    }
}
