<?php

declare(strict_types=1);

namespace Ngramx\Postmaclone\Anonymizer;

use Ngramx\Config\Schema\Postmaclone\ColumnRule;
use Ngramx\Config\Schema\Postmaclone\PostmacloneConfig;
use Ngramx\Config\Schema\Postmaclone\TableRule;
use Ngramx\Postmaclone\Exception\PostmacloneException;
use Ngramx\Postmaclone\FakerMethodResolver;

class SqlEmitter
{
    public function __construct(
        private readonly FakerMethodResolver $faker,
        private readonly SqlDialect $dialect,
        private readonly string $testPassword = PostmacloneConfig::DEFAULT_TEST_PASSWORD,
        private readonly int $chunkSize = 500,
    ) {
    }

    /**
     * @param array<string, TableRule> $tables
     * @param array<string, list<array<string, mixed>>> $rowsByTable
     */
    public function emit(array $tables, array $rowsByTable): string
    {
        $parts = [
            '-- Generated by ngramx postmaclone --sql',
            '-- Do not run against production. Anonymization rules are project-owned.',
            '',
        ];

        foreach ($tables as $tableName => $tableRule) {
            $rows = $rowsByTable[$tableName] ?? [];
            if ($rows === []) {
                $parts[] = "-- No rows found for table {$tableName}";
                $parts[] = '';
                continue;
            }

            $pk = $tableRule->primaryKey ?? $this->guessPrimaryKey($rows);
            if ($pk === null) {
                throw new PostmacloneException(
                    "Cannot emit SQL for table '{$tableName}': no primary key. Set tables.{$tableName}.primary_key"
                );
            }

            $parts = array_merge($parts, $this->emitTableUpdates($tableRule, $rows, $pk));
            $parts[] = '';
        }

        return implode("\n", $parts);
    }

    /**
     * @param list<array<string, mixed>> $rows
     * @return list<string>
     */
    private function emitTableUpdates(TableRule $table, array $rows, string $pk): array
    {
        $lines = ["-- {$table->table}"];
        $buffer = [];

        foreach ($rows as $row) {
            if (!array_key_exists($pk, $row)) {
                continue;
            }

            $sets = [];
            foreach ($table->columns as $column => $rule) {
                if (!array_key_exists($column, $row)) {
                    continue;
                }

                $current = $row[$column];
                // Opt-in column only — unlisted columns never appear in $table->columns
                if ($current === null && $rule->preserveNulls) {
                    continue;
                }

                $sets[] = $this->dialect->quoteIdentifier($column)
                    . ' = '
                    . $this->dialect->quoteLiteral($this->fakeValue($rule));
            }

            if ($sets === []) {
                continue;
            }

            $buffer[] = 'UPDATE '
                . $this->dialect->quoteIdentifier($table->table)
                . ' SET '
                . implode(', ', $sets)
                . ' WHERE '
                . $this->dialect->quoteIdentifier($pk)
                . ' = '
                . $this->dialect->quoteLiteral($row[$pk])
                . ';';

            if (count($buffer) >= $this->chunkSize) {
                $lines = array_merge($lines, $buffer);
                $buffer = [];
            }
        }

        return array_merge($lines, $buffer);
    }

    private function fakeValue(ColumnRule $rule): mixed
    {
        if ($rule->faker === 'password') {
            return password_hash($this->testPassword, PASSWORD_BCRYPT);
        }

        return $this->faker->generate($rule->faker, $rule->unique);
    }

    /**
     * @param list<array<string, mixed>> $rows
     */
    private function guessPrimaryKey(array $rows): ?string
    {
        if ($rows === []) {
            return null;
        }
        $first = $rows[0];
        foreach (['id', 'uuid', 'guid'] as $candidate) {
            if (array_key_exists($candidate, $first)) {
                return $candidate;
            }
        }

        return array_key_first($first);
    }
}
