<?php

declare(strict_types=1);

namespace Ngramx\Tests\Unit\Docker;

use Ngramx\Docker\ComposeBuildBaseline;
use Ngramx\Docker\ComposeFiles;
use PHPUnit\Framework\TestCase;

class ComposeBuildBaselineTest extends TestCase
{
    private string $tempDir;

    protected function setUp(): void
    {
        $this->tempDir = sys_get_temp_dir() . '/ngramx-compose-baseline-' . uniqid();
        mkdir($this->tempDir, 0755, true);
        file_put_contents($this->tempDir . '/docker-compose.yml', "services:\n  app:\n    build: .\n");
    }

    protected function tearDown(): void
    {
        $this->removeDirectory($this->tempDir);
    }

    public function test_it_hashes_the_full_compose_stack_including_override(): void
    {
        $compose = $this->tempDir . '/docker-compose.yml';
        file_put_contents(
            $this->tempDir . '/' . ComposeFiles::OVERRIDE_FILE,
            "# Generated by Ngramx CLI\nservices:\n  app:\n    ports: ['8080:80']\n"
        );

        $baseline = new ComposeBuildBaseline();
        $hashes = $baseline->hashInputs($compose);

        $this->assertArrayHasKey('docker-compose.yml', $hashes);
        $this->assertArrayHasKey(ComposeFiles::OVERRIDE_FILE, $hashes);
    }

    public function test_it_detects_changes_in_generated_override_content(): void
    {
        $compose = $this->tempDir . '/docker-compose.yml';
        $override = $this->tempDir . '/' . ComposeFiles::OVERRIDE_FILE;
        file_put_contents($override, "# Generated by Ngramx CLI\nservices:\n  app:\n    ports: ['8080:80']\n");

        $baseline = new ComposeBuildBaseline();
        $baseline->record($compose);

        file_put_contents($override, "# Generated by Ngramx CLI\nservices:\n  app:\n    ports: ['8081:80']\n");

        $this->assertSame([], $baseline->changedInputs($compose));
    }

    public function test_it_flags_changes_to_the_base_compose_file(): void
    {
        $compose = $this->tempDir . '/docker-compose.yml';
        $baseline = new ComposeBuildBaseline();
        $baseline->record($compose);

        file_put_contents($compose, "services:\n  app:\n    build: .\n    environment:\n      FOO=bar\n");

        $this->assertSame(['docker-compose.yml'], $baseline->changedInputs($compose));
    }

    public function test_it_flags_changes_to_user_override(): void
    {
        $compose = $this->tempDir . '/docker-compose.yml';
        $user = $this->tempDir . '/' . ComposeFiles::USER_FILE;
        file_put_contents($user, "services:\n  app:\n    environment:\n      FOO=bar\n");

        $baseline = new ComposeBuildBaseline();
        $baseline->record($compose);

        file_put_contents($user, "services:\n  app:\n    environment:\n      FOO=baz\n");

        $this->assertSame([ComposeFiles::USER_FILE], $baseline->changedInputs($compose));
    }

    private function removeDirectory(string $dir): void
    {
        if (!is_dir($dir)) {
            return;
        }

        foreach (scandir($dir) ?: [] as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $path = $dir . '/' . $item;
            is_dir($path) ? $this->removeDirectory($path) : unlink($path);
        }

        rmdir($dir);
    }
}
